### ISSUE TITLE
Authorize monolog v2

### ISSUE THREAD

**Issue by thiphamyp** [PaylineByMonext/payline-php-sdk#49]
Your library forces installation of monolog v1.
Can you please installation of monolog v2?

Thank you

**Comment by CharlelieBouvier** [comment]
Please let me know if this is a big problem for you

**Comment by tristanbes** [comment]
It is a big problem; You are a library; and because of your hard constraints, you are preventing other applications to use either monolog 2.

It shouldn't be the case; 

Moreover it's highly unlikely that you used advanced features that is not compliant with monolog v2 https://github.com/Seldaek/monolog/blob/master/UPGRADE.md


You should allow monolog v2 AND v1 (because v2 is more restrictive when it comes to PHP support only 7.2+)

like they did there: 
https://github.com/symfony/monolog-bundle/blob/master/composer.json#L24

**Comment by tristanbes** [comment]
PS: I have someone intenrally that will submit a PR to address that;

**Comment by CharlelieBouvier** [comment]
Hello,

Well, I had no idea about your constraints, that's why I asked, and maybe look into it later.

So please, be gentle in your messages.

I'm waiting for a PR and will test it asap after that.

Regards,
Charlélie

**Comment by tristanbes** [comment]
There were no hard feeling in my message; sorry if you felt this way.

PS: It's especially because you have no idea about the application constraints that you should be as "loose" (authorize as multiple & recent version) as possible

Thank you.
